MediaMarktSaturn/technolinator

src/main/java/com/mediamarktsaturn/technolinator/sbom/DependencyTrackClient.java
src/test/java/com/mediamarktsaturn/technolinator/sbom/DependencyTrackClientTest.java

Handling of an edge case that ensures the current version of a project is always _active_.
If you switched your default branch forth and back you could end up in a situation with your current version being inactive.
E.g. active branch from _dev_ (step 1) to _master_ (step 2) and back again to _dev_ (step 3).
Formally step 2 deactivated _dev_ (`active: false`) and _master_ had the property `active` not set explicitly which is handled as _active_ by dtrack. If you now switched back to version `dev` as step 3 the property `active: false` still remained. This results in all versions having the property `active: false`.
This patch now always sets the property `active: true` on the current submitted version.

chore(bom-upload): Always set current project as active

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/workflows/ci.yml

Add templates for bug report and feature request, to guide users with
submitting new issues.
See also:
- https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests

chore(github): add issue templates

---

.github/workflows/ci.yml
.releaserc

Define all possible commit types and their corresponding releases.
And add the conventional commits preset in release-note-generator
plugin, so that a more useful release note can be generated.
See also:
- https://github.com/semantic-release/commit-analyzer#rules-definition
- https://github.com/semantic-release/release-notes-generator/issues/153#issuecomment-555152563

ci(actions): adjust release creation

---

.github/workflows/ci.yml

Required dependencies need to be installed before `semantic-release` can be invoked.
Related to https://github.com/MediaMarktSaturn/technolinator/pull/189.

fix(actions): fix CI on release creation

---

.github/workflows/ci.yml

Cancel any concurrent builds for any non-main branches to not wasted
build minutes.
See also:
- https://docs.github.com/en/actions/using-jobs/using-concurrency

ci(actions): add concurrency to ci workflow

---

.github/workflows/ci.yml

Build on main, triggered by dependabot merges (by commented on the
pull request with for example `@dependabot merge`), is failing because
dependabot actor does not have sufficient permissions.

ci(actions): skip ci on main for dependabot merges

---

.github/actions/install-requirements/action.yaml
.github/workflows/ci.yml
.github/workflows/verify.yml

Install all requirements in a composite action, which can be re-used
in both ci and verify workflows to reduce code duplication.
Also sanity the input for grype and sbomqs versions, because renovate
update these sometimes with and other times without a `v` prefix.

ci(actions): add composite action install-requirements

---

src/main/java/com/mediamarktsaturn/technolinator/sbom/CdxgenClient.java
src/test/java/com/mediamarktsaturn/technolinator/CustomTestProfiles.java
src/test/java/com/mediamarktsaturn/technolinator/sbom/CdxgenClientOptionalEnvTest.java

SmallRyeConfig `getValue` doesn't allow the provided configured value to
be empty, therefore use `getOptionalValue` instead.
See also: https://github.com/eclipse/microprofile-config/pull/407
Fixes #303

fix: adjust parsing of app.allowed_env_substitutions

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/workflows/assign_issue.yml

Add a new workflow to thank the issue creator. And mention the team
instead of assign the issue to a small list of people, so that more
members are made aware of the issue.
Based on this guide
- https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added

ci(actions): add workflow to comment on opened issue

---

src/main/java/com/mediamarktsaturn/technolinator/events/DispatcherBase.java
src/main/resources/application.properties
src/test/java/com/mediamarktsaturn/technolinator/CustomTestProfiles.java
src/test/java/com/mediamarktsaturn/technolinator/events/OnPushDispatcherTest.java
src/test/java/com/mediamarktsaturn/technolinator/events/OnPushDispatcherWithDisabledCommitStatusWriteTest.java

Add a new application configuration to disable the commit status update
for all repositories in case permissions are not yet given.
Closes #306.

feat: make commit status update configurable

---

src/test/java/com/mediamarktsaturn/technolinator/sbom/DependencyTrackClientTest.java

Based on the test error message, it looks like the payload, returned
when fetching the recorded requests, is not sorted as expected and
therefore causes the `DependencyTrackClientTest.testSuccessfulUpload`
test to fail from time to time.
Fixes #208.

test: fix flaky successful upload test case

---

.github/workflows/close_dependabot_pr.yaml

Use a new workflow to automatically close any dependabot pull requests
created for `src/test` because the feature to ignore specific folders
isn't yet available by dependabot core team.
See also https://github.com/superbrothers/close-pull-request
Solved #229.

ci(actions): close dependabot pull requests for src/test

---

.github/workflows/ci.yml

Currently any standalone changes to the readme don't trigger the CI,
which causes the pull request to be blocked because the CI build is
set as required.
To workaround this, use a prep job to check for relevant changes and
trigger a skip job for trivial changes like readme updates.

ci(actions): skip ci for non relevant changes

---

catalog-info.yaml

This pull request adds a metadata file to assign your repository to the corresponding MMS entities. Please check and replace the placeholders with the values valid for your team and repository.
The mapping is part of the Security initiative and will be enforced for all repositories. Please do not ignore and discard this pull request. Instead, adjust the following values carefully to enable cataloging with the Backstage tool.
Please note that the pull request should be reviewed and merged **no later than February 29, 2024**.
\<TEAM\>
\<PRODUCT_ID\>
\<APP_ID\>
\<TYPE\>
\<LIFECYCLE\>
\<OWNER\>
The decision has not yet been made, but we would like to introduce the Backstage as a developer portal. The tool was chosen because it is the best fit for us. The metadata format was defined together …

[CAPA-1004] Assignment of repository to application/product

---

pom.xml

Release: https://github.com/quarkusio/quarkus/releases/tag/3.8.1
Changelog: https://github.com/quarkusio/quarkus/compare/3.7.4...3.8.1

build(mvn): bump quarkus from 3.7.4 to 3.8.1

---

.github/workflows/ci.yml

Add the `pull_request_target` trigger, so that pull requests from a
fork will also start a build. Otherwise they can't be verified.
A downside to this is that changes to the CI workflow can't be directly
verified on a pull request anymore without some workarounds, because
the CI will now run in the context of the base of the pull request.
Closes #378.
See also:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

ci(actions): adjust workflow triggers

---

.github/workflows/ci.yml

With the check using `github.ref` and dependabot as an actor, the build
is skipped. Previously, only the `push` trigger exists and will trigger
the workflow. As the `pull_request_target` has been added to also allow
pull requests from forks to trigger the workflow, the check needs to be
adjusted.
Related to:
- https://github.com/MediaMarktSaturn/technolinator/issues/378

ci(actions): adjust build trigger check for dependabot

---

.github/workflows/ci.yml
src/test/java/com/mediamarktsaturn/technolinator/git/RepositoryServiceTest.java

The `GHFileNotFoundException` message has been changed and therefore
the test validation needs to be adjusted.
Also switch back `push` only trigger, because the`pull_request_target`
trigger runs on the main branch context, so it won't verify the actual
changes in a pull request.
Therefore, re-open the issue #378.

test: adjust RepositoryServiceTest.testInvalidBranch

---

.github/workflows/ci.yml

Currently the builds on main are failing with the error
`System.IO.IOException: No space left on device`.
See for example the runs
- https://github.com/MediaMarktSaturn/technolinator/actions/runs/8566012762
- https://github.com/MediaMarktSaturn/technolinator/actions/runs/8566139722
Therefore, follow the suggestion in this comment
- https://github.com/orgs/community/discussions/26351#discussioncomment-3251595
to free up space on GitHub runner, before running the CI.

ci(actions): fix no space left on device error

---

.github/workflows/ci.yml

The latest major version (`8.0.0`) containing breaking changes, which
are not yet included in release-notes-generator.
Therefore, pin its version to the previous release for now to not
block any further releases.
See issue:
- https://github.com/semantic-release/release-notes-generator/issues/633

fix(ci): pin conventional-changelog-conventionalcommits to 7.0.2

---

pom.xml

Release: https://github.com/quarkusio/quarkus/releases/tag/3.11.2
Changelog: https://github.com/quarkusio/quarkus/compare/3.11.1...3.11.2

build(mvn): bump quarkus from 3.11.1 to 3.11.2

---

.github/workflows/ci.yml
.github/workflows/renovate.yml
.github/workflows/verify.yml
pom.xml
src/test/java/com/mediamarktsaturn/technolinator/sbom/GrypeClientTest.java

GrypeClientTests fail in github actions with exit code 1 of grype.
That's not reproducible locally, thus disabling tests for now.

build(deps): Update some dependencies

---

.github/workflows/ci.yml

Use the `scacap/action-surefire-report`
to publish the test reports from maven surefire,
so that it's easier to identify the actual failing tests,
without having going through the whole logs.
See also:
- https://github.com/scacap/action-surefire-report

chore(action): publish test reports on failure

---

.editorconfig
.github/renovate.json

See also:
- https://docs.renovatebot.com/configuration-options/#configmigration
Also set the indentation for json files to 2, and reformat the current
renovate configuration file.

chore(renovate): enable auto config migration

---

src/main/docker/Dockerfile

See also https://maven.apache.org/docs/history.html
Similar to
- https://github.com/MediaMarktSaturn/technolinator/pull/765

build(docker): bump maven from 3.9.10 to 3.9.11
